organization     = "my-org"
project          = "my-project" 
workspace        = "my-workspace"
sp_name          = "tfc-federated-credential"
role             = "Contributor"
subscription_id  = "bc884483-24ef-40c5-b8d4-0c35a50ca8f8"
